server:
  port: 8082
cors:
  allowed-origins: "*"
adapters:
  r2dbc:
    host: "auth-db"
    port: 5432
    database: "authdb"
    schema: "public"
    username: "authuser"
    password: "authpass"
security:
  jwt:
    secret: "kYf5mJvQx6jR1LWYiwvhP2Z5gTw4Xt4lUOpd4XyD5rk=" # debe coincidir con auth-service
    expiration: 3600 # 1h en s
